Social_Media.Web/Controllers/Account/Role/RoleController.cs
using Microsoft.AspNetCore.Mvc;

namespace Social_Media.Web.Controllers
{
    public class RoleController : Controller
    {
        public IActionResult EditRole()
        {
            return View();
        }

        public IActionResult CreateRole()
        {
            return View();
        }
    }
}

Social_Media.Web/Controllers/Account/User/ActionWithPassword/PasswordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.Data.ViewModels.UserViewModels.PasswordViewModels;
using Social_Media.EntityFramework;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [AllowAnonymous]
    public class PasswordController : Controller
    {
        public IActionResult ForgotPassword()
        {
            return View(new ForgotPasswordViewModel());
        }

        public IActionResult ResetPassword(string email)
        {
            return View(new ResetPasswordViewModel
            {
                Email = email
            });
        }
    }
}

Social_Media.Web/Controllers/Chat/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Social_Media.Data.DataModels.Entities;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private IRepositoryEntityFramework _contextEF;
        private UserManager<User> _userManager;
        public ChatController(IRepositoryEntityFramework entityFramework, UserManager<User> userManager)
        {
            _contextEF = entityFramework;
            _userManager = userManager;
        }

        public IActionResult Chats()
        {
            return View(_contextEF.GetAll<Chat>().AsEnumerable().Where(chat => chat.PostId == null));
        }

        public async Task<IActionResult> UserChats(string userName)
        {
            User user = await _userManager.FindByNameAsync(userName);

            if (user != null)
            {
                return View(_contextEF.GetAll<Chat>()
                    .AsEnumerable()
                    .Where(chat => chat.CreaterId == user.Id && chat.PostId == null));
            }
            else
            {
                return RedirectToAction("Posts", "PostWall");
            }
            
        }

        public IActionResult CreateChat()
        {
            return View(new Chat());
        }

        public async Task<IActionResult> ChatingRoom(Guid chatId)
        {
            Chat chat = await _contextEF.GetAll<Chat>()
                .Include(chat => chat.UserMassage)
                .ThenInclude(massage => massage.Creater)
                .FirstOrDefaultAsync(chat => chat.Id == chatId);

            User user = await _userManager.Users.
                FirstOrDefaultAsync(user => user.UserName == User.Identity.Name);

            if (chat != null)
            {
                ViewBag.IdUser = user.Id;
                return View(chat);
            }
            return RedirectToAction("Chats");
        }
    }
}

Social_Media.Web/Controllers/Chat/CrudChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities;
using Social_Media.Data.DataModels.Entities.Interfaces;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class CrudChatController : Controller
    {
        private IRepositoryEntityFramework _contextEF;
        private UserManager<User> _userManager;
        public CrudChatController(IRepositoryEntityFramework entityFramework, UserManager<User> userMangaer)
        {
            _contextEF = entityFramework;
            _userManager = userMangaer;
        }

        [HttpPost]
        public async Task<IActionResult> CreateChat(Chat chat, string createrName, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(createrName);

                chat.CreateAt = DateTime.Now;
                chat.UpdateAt = DateTime.Now;
                chat.UserMassage = new List<Massage>();
                if (user != null)
                {
                    chat.CreaterId = user.Id;
                }

                await _contextEF.CreateAsync(chat);

                if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                {
                    return RedirectToAction("Chats", "Chat");
                }
                else
                {
                    return Redirect(returnUrl);
                }
            }
            return RedirectToAction("Chats", "Chat");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateChat(Chat chat, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                Chat chatContext = await _contextEF.GetAll<Chat>().FirstOrDefaultAsync(chatContext => chatContext.Id == chat.Id);
                if (chatContext != null)
                {
                    chatContext.UpdateAt = DateTime.Now;
                    chatContext.Name = chat.Name;

                    await _contextEF.UpdateAsync(chatContext);

                    if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Chats", "Chat");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }

            }
            return RedirectToAction("EditChat", "Chat", new {chatId = chat.Id});
        }

        [HttpPost]
        public async Task<IActionResult> RemovetChat(Guid chatId, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                Chat chat = await _contextEF.GetAll<Chat>().FirstOrDefaultAsync(chat => chat.Id == chatId);

                if (chat != null)
                {
                    await _contextEF.RemovetAsync(chat);

                    if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Chats", "Chat");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    return BadRequest("Chat not removed");
                }
            }
            ViewBag.Exeption = "Error";
            return RedirectToRoute(returnUrl);
        }
    }
}

Social_Media.Web/Controllers/Massage/CrudMassageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities;
using Social_Media.Data.DataModels.Entities.Interfaces;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.Data.ViewModels.MassageViewModels;
using Social_Media.EntityFramework;
using Social_Media.Web.Model.UserModel;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class CrudMassageController : Controller
    {
        private IRepositoryEntityFramework _contextEF;
        private UserManager<User> _userManager;
        public CrudMassageController(IRepositoryEntityFramework entityFramework, UserManager<User> userMangaer)
        {
            _contextEF = entityFramework;
            _userManager = userMangaer;
        }

        [HttpPost]
        public async Task<IActionResult> CreateMassageToChat(MassageAndChatIdViewModel viewModel, string createrName, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                Chat chat = await _contextEF.GetAll<Chat>().FirstOrDefaultAsync(chat => chat.Id == viewModel.ChatId);
                User user = await _userManager.FindByNameAsync(createrName);
                if (chat != null)
                {
                    chat.UpdateAt = DateTime.Now;
                    viewModel.Massage.UsingChat = chat;
                }

                if (user != null)
                {
                    viewModel.Massage.CreaterId = user.Id;
                }

                await _contextEF.CreateAsync(viewModel.Massage);
            }
            if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
            {
                return RedirectToAction("ChatingRoom", "Chat", new { chatId = viewModel.ChatId });
            }
            else
            {
                return Redirect(returnUrl);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateMassageToPrivateChat(MassageAndPrivateChatIdViewModel viewModel, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                PrivateChat privateChat = await _contextEF.GetAll<PrivateChat>()
                    .FirstOrDefaultAsync(chat => chat.Id == viewModel.PrivateChatId);

                User user = await _userManager.FindByNameAsync(viewModel.UserName);
                if (privateChat != null)
                {
                    privateChat.UpdateAt = DateTime.Now;
                    viewModel.Massage.PrivateChat = privateChat;

                }

                if (user != null)
                {
                    viewModel.Massage.CreaterId = user.Id;
                }

                await _contextEF.CreateAsync(viewModel.Massage);

            }
            if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
            {
                return RedirectToAction("PrivateChatingRoom", "PrivateChat", new
                {
                    model = new FriendNameAndUserName
                    {
                        UserName = viewModel.UserName,
                        FriendName = viewModel.FriendName,
                    }
                });
            }
            else
            {
                return Redirect(returnUrl);
            }

        }

        [HttpPost]
        public async Task<IActionResult> UpdateMassage(MassageAndChatIdViewModel viewModel, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                Massage massageContext = await _contextEF.GetAll<Massage>()
                    .FirstOrDefaultAsync(massageContext => massageContext.Id == viewModel.Massage.Id);
                if (massageContext != null)
                {
                    massageContext.UpdateAt = DateTime.Now;
                    massageContext.Discription = viewModel.Massage.Discription;
                    await _contextEF.UpdateAsync(massageContext);
                }
                else
                {
                    return BadRequest("Massage not updated");
                }
            }
            if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
            {
                return RedirectToAction("ChatingRoom", "Chat", new { chatId = viewModel.ChatId });
            }
            else
            {
                return Redirect(returnUrl);
            };
        }

        [HttpPost]
        public async Task<IActionResult> RemovetMassage(Guid massageId, Guid chatId, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                Massage massage = await _contextEF.GetAll<Massage>().FirstOrDefaultAsync(massage => massage.Id == massageId);
                if (massage != null)
                {
                    await _contextEF.RemovetAsync(massage);
                }
                else
                {
                    return BadRequest("Massage not removed");
                }
            }
            if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
            {
                return RedirectToAction("ChatingRoom", "Chat", new { chatId = chatId });
            }
            else
            {
                return Redirect(returnUrl);
            }
        }
    }
}

Social_Media.Web/Controllers/PostWall/CrudPostWallController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities;
using Social_Media.Data.DataModels.Entities.Interfaces;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class CrudPostWallController : Controller
    {
        private IRepositoryEntityFramework _contextEF;
        private UserManager<User> _userManager;

        public CrudPostWallController(IRepositoryEntityFramework entityFramework, UserManager<User> userManager)
        {
            _contextEF = entityFramework;
            _userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(Post post, string createrName, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                post.Liked = 0;
                User user;

                post.CreateAt = DateTime.Now;
                post.UpdateAt = DateTime.Now;

                Chat chatForPost = new Chat()
                {
                    Name = post.Title,
                    CreateAt = post.CreateAt,
                    UpdateAt = post.UpdateAt,
                    UserMassage = new List<Massage>(),

                };

                if (createrName != null)
                {
                    user = await _userManager.FindByNameAsync(createrName);
                    post.CreaterId = user.Id;
                    chatForPost.CreaterId = user.Id;
                }
                else
                {
                    return RedirectToAction("Posts", "PostWall");
                }


                post.UsingChat = chatForPost;
                await _contextEF.CreateAsync(post);

                if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                {
                    return RedirectToAction("Posts", "PostWall");
                }
                else
                {
                    return Redirect(returnUrl);
                }
            }
            return RedirectToAction("CreatePost", "PostWall");
        }

        [HttpPost]
        public async Task<IActionResult> RemovetPost(Guid postId, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                Post post = await _contextEF.GetAll<Post>().FirstOrDefaultAsync(post => post.Id == postId);

                if (post != null)
                {
                    await _contextEF.RemovetAsync(post);

                    if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Posts", "PostWall");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    return BadRequest("Post not removed");
                }

            }
            ViewBag.Exeption = "Error";
            return RedirectToRoute(returnUrl);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePost(Post post, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                Post postContext = await _contextEF.GetAll<Post>().FirstOrDefaultAsync(postContext => postContext.Id == post.Id);
                if (postContext != null)
                {
                    postContext.UpdateAt = DateTime.Now;
                    postContext.Discription = post.Discription;
                    postContext.Title = post.Title;
                    await _contextEF.UpdateAsync(postContext);

                    if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("MyProfile", "Account", new {userName = User.Identity.Name});
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
            }
            return RedirectToAction("EditPost", "PostWall", new {postId = post.Id});
        }
    }
}

Social_Media.Web/Views/Admin/ChatMassages.cshtml
@model Chat

@{
    Layout = "_AdminChatingRoomLayout";
    ViewBag.Title = "Check massages of Chat";
}

@foreach (Massage massage in Model.UserMassage.OrderBy(massage => massage.CreateAt))
{
    <div class="my-3">
        <div>
            <form asp-action="RemovetMassage" asp-controller="CrudMassage" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                <input hidden="hidden" name="massageId" value="@massage.Id">
                <button type="submit" class="btn btn-danger p-1">Remove</button>
            </form>
        </div>
        <div class="card">
            <div class="card-header text-center">
                <div class="m-1">
                    <h5>@massage.Creater.UserName</h5>
                </div>
            </div>
            <button class="btn btn-secondary p-lg-0 text-center" type="button" data-bs-toggle="collapse" data-bs-target="#collapse@(massage.Id)" aria-expanded="false" aria-controls="collapse@(massage.Id)">
                <p class="p-0 fs-6">Discription</p>
            </button>
            <div class="card-body p-0 d-flex">
                <div class="d-flex m-1">
                    <div class="collapse-show" id="collapse@(massage.Id)">
                        <div class="card-body">
                            <h5>@massage.Discription</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Social_Media.Web/Views/Admin/Chats.cshtml
@model IEnumerable<Chat>

@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Admin chat";
}

@foreach (Chat chat in Model.Where(chat => chat.PostId == null))
{
    <div class="m-3">
        <div class="justify-content-between d-flex">
            <div class="justify-content-start d-flex">
                <div class="mx-1">
                    <form asp-action="RemovetChat" asp-controller="CrudChat" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                        <input hidden="hidden" name="chatId" value="@chat.Id">
                        <button class="btn btn-danger p-1" type="submit">Remove</button>
                    </form>
                </div>
                <div class="mx-1">
                    <form asp-action="EditChat" asp-controller="Chat" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                        <input hidden="hidden" name="chatId" value="@chat.Id">
                        <button class="btn btn-warning p-1">Edit</button>
                    </form>
                </div>
            </div>
            <div>
                <form asp-action="ChatMassages" asp-controller="Admin" asp-route-chatId="@chat.Id">
                    <button type="submit" class="btn btn-primary p-1">Massages</button>
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-header text-center">
                <h4>@chat.Name</h4>
            </div>
            <div class="card-body text-center">
                <div>
                    <h5>Creater: @chat.Creater.UserName</h5>
                </div>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-between">
                    <div>
                        <h5>Create:</h5>
                    </div>
                    <div>
                        <h5>@chat.CreateAt</h5>
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <div>
                        <h5>Update:</h5>
                    </div>
                    <div>
                        <h5>@chat.UpdateAt</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Social_Media.Web/Views/Admin/Posts.cshtml
@model IEnumerable<Post>

@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Admin posts";
}
<div>
    @foreach (Post post in Model)
    {
        <div class="m-3">
            <div class="d-flex justify-content-between">
                <div class="justify-content-start d-flex">
                    <div class="mx-1">
                        <form asp-action="RemovetPost" asp-controller="CrudPostWall" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                            <input hidden="hidden" name="postId" value="@post.Id">
                            <button type="submit" class="btn btn-danger p-1">Remove</button>
                        </form>
                    </div>
                    <div class="mx-1">
                        <form asp-action="EditPost" asp-controller="PostWall" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                            <input hidden="hidden" name="postId" value="@post.Id">
                            <button type="submit" class="btn btn-warning p-1">Edit</button>
                        </form>
                    </div>
                </div>
                <div>
                    <div>
                        <form asp-action="ChatMassages" asp-controller="Admin" asp-route-chatId="@post.UsingChat.Id">
                            <button type="submit" class="btn btn-primary p-1">Massages of comment</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header text-center">
                    <h4>@post.Title</h4>
                </div>
                <button class="btn btn-secondary p-0 text-center" type="button" data-bs-toggle="collapse" data-bs-target="#collapse@(post.Id)" aria-expanded="false" aria-controls="collapse@(post.Id)">
                    <p class="p-0 fs-5">Discription<p/>
                </button>
                <div class="collapse" id="collapse@(post.Id)">
                    <div class="card-body">
                        <h4>@post.Discription</h4>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <div>
                        <h5>Creater: @post.Creater.UserName</h5>
                    </div>
                    <div>
                        <h5>@post.CreateAt</h5>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Social_Media.Web/Views/Admin/Roles.cshtml
@model IEnumerable<IdentityRole>

@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Admin Roles";
}

@foreach (IdentityRole role in Model)
{
    <div class="my-3">
        <div class="card">
            <div class="card-body d-flex justify-content-between">
                <div>
                    <h5>Role name: @role.Name</h5>
                </div>
                <div>
                    <p class="fs-5">Id: @role.Id</p>
                </div>
            </div>
        </div>
    </div>
}

Social_Media.Web/Views/Admin/Users.cshtml
@model IEnumerable<User>

@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Admin users";
}

@foreach (User user in Model)
{
    <div class="my-3">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <div>
                    <h5>Name: @user.UserName</h5>
                </div>
                <div>
                    <h5>Id: @user.Id</h5>
                </div>
            </div>
            <button class="btn btn-secondary p-0 text-center" type="button" data-bs-toggle="collapse" data-bs-target="#collapse@(user.Id)" aria-expanded="false" aria-controls="collapse@(user.Id)">
                <p class="p-0 fs-5">Information<p/>
            </button>
            <div class="collapse" id="collapse@(user.Id)">
                <div class="card-body">
                    <div class="row d-flex justify-content-between mx-3">
                        <div class="col-1 w-auto">
                            <div>
                                <p class="fs-5">Count friends: @user.UserFriends.Count()</p>
                            </div>
                            <div>
                                <p class="fs-5">Count follow: @user.FollowingUser.Count()</p>
                            </div>
                        </div>
                        <div class="col-2 w-auto">
                            <div>
                                <p class="fs-5">Submitting posts: @user.Posts.Count()</p>
                            </div>
                            <div>
                                <p class="fs-5">Creating chats: @user.OwnerChats.Count()</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}