Social_Media.Web/Controllers/Account/User/OtherUser/OtherAccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.Data.ViewModels.UserViewModels;
using Social_Media.EntityFramework;
using Social_Media.Web.Model.UserModel;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class OtherAccountController : Controller
    {
        private UserContextEntityFramework _userContextEF;
        public OtherAccountController(UserContextEntityFramework userContextEF)
        {
            _userContextEF = userContextEF;
        }

        public async Task<IActionResult> OtherProfile(string userName)
        {
            User user = await _userContextEF.GetAllUsers()
                .Include(user => user.UserFriends)
                .FirstOrDefaultAsync(user => user.UserName == userName);

            if (user != null)
            {
                return View(user);
            }
            return RedirectToAction("AllUsers");
        }

        public async Task<IActionResult> MyFriends(string userName)
        {
            User user = await _userContextEF.GetAllUsers()
                .Include(user => user.FollowingUser)
                .Include(user => user.UserFriends)
                    .ThenInclude(userAnother => userAnother.PrivateChats)
                .Include(user => user.UserFriends)
                    .ThenInclude(userAnother => userAnother.UserFriends)
                .Include(user => user.PrivateChats)
                .FirstOrDefaultAsync(user => user.UserName == userName);

            if (user != null)
            {
                return View(user);
            }
            return RedirectToAction("Posts", "PostWall");
        }


        public async Task<IActionResult> AllUsers()
        {
            User user = await _userContextEF
                .GetAllUsers()
                .Include(userInclude => userInclude.UserFriends)
                .FirstOrDefaultAsync(user => user.UserName == HttpContext.User.Identity.Name);

            return View(new UserAndAllUsersViewModel
            {
                UsersFromContext = _userContextEF.GetAllUsers()
                .Where(userContext =>
                       userContext.UserName != user.UserName &&
                       !user.UserFriends.Contains(userContext))
                .ToList(),

                User = user
            });
        }
    }   
}

Social_Media.Web/Controllers/Chat/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Social_Media.Data.DataModels.Entities;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private IRepositoryEntityFramework _contextEF;
        private UserManager<User> _userManager;
        public ChatController(IRepositoryEntityFramework entityFramework, UserManager<User> userManager)
        {
            _contextEF = entityFramework;
            _userManager = userManager;
        }

        public IActionResult Chats()
        {
            return View(_contextEF.GetAll<Chat>().AsEnumerable().Where(chat => chat.PostId == null));
        }

        public async Task<IActionResult> UserChats(string userName)
        {
            User user = await _userManager.FindByNameAsync(userName);

            if (user != null)
            {
                return View(_contextEF.GetAll<Chat>()
                    .AsEnumerable()
                    .Where(chat => chat.CreaterId == user.Id && chat.PostId == null));
            }
            else
            {
                return RedirectToAction("Posts", "PostWall");
            }
            
        }

        public IActionResult CreateChat()
        {
            return View(new Chat());
        }

        public async Task<IActionResult> ChatingRoom(Guid chatId)
        {
            Chat chat = await _contextEF.GetAll<Chat>()
                .Include(chat => chat.UserMassage)
                .ThenInclude(massage => massage.Creater)
                .FirstOrDefaultAsync(chat => chat.Id == chatId);

            User user = await _userManager.Users.
                FirstOrDefaultAsync(user => user.UserName == User.Identity.Name);

            if (chat != null)
            {
                ViewBag.IdUser = user.Id;
                return View(chat);
            }
            return RedirectToAction("Chats");
        }
    }
}

Social_Media.Web/Controllers/PrivateChat/PrivateChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.EntityFramework;
using Social_Media.Web.Model.UserModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class PrivateChatController : Controller
    {
        private IRepositoryEntityFramework _contextEF;
        private UserContextEntityFramework _userContextEF;
        public PrivateChatController(IRepositoryEntityFramework entityFramework, UserContextEntityFramework userEntityFramework)
        {
            _contextEF = entityFramework;
            _userContextEF = userEntityFramework;
        }

        public async Task<IActionResult> PrivateChatingRoom(FriendNameAndUserName model)
        {
            var userContext = _userContextEF.GetAllUsers()
                .Include(user => user.PrivateChats);

            User user = await userContext
                .FirstOrDefaultAsync(user => user.UserName == model.UserName);

            User friendUser = await userContext
                .FirstOrDefaultAsync(user => user.UserName == model.FriendName);


            foreach (PrivateChat privateChat in user.PrivateChats)
            {
                var id = privateChat.Id;
                foreach (PrivateChat friendPrivateChat in friendUser.PrivateChats)
                {
                    var chatId = friendPrivateChat.Id;

                    if (id == chatId)
                    {
                       var privateChatContext = await _contextEF.GetAll<PrivateChat>()
                            .Include(privateChat => privateChat.Massages)
                            .FirstOrDefaultAsync(privateChat => privateChat.Id == id);
                        ViewBag.IdUser = user.Id;

                        return View(privateChatContext);
                    }
                }
            }

            return RedirectToAction("MyFriends", "Account", new {userName = user.UserName});
        }

        public async Task<IActionResult> MyPrivateChat(string userName)
        {
            User user = await _userContextEF.GetAllUsers()
                .Include(user => user.PrivateChats)
                    .ThenInclude(privateChat => privateChat.Members)
                .Include(user => user.Massages)
                .FirstOrDefaultAsync(user => user.UserName == userName);

            if (user != null)
            {
                return View(user.PrivateChats.AsEnumerable());
            }
            else
            {
                return RedirectToAction("Posts", "PostWall");
            }
        }
    }
}

Social_Media.Web/Views/Shared/_AdminChatingRoomLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/bundle.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <div class="content">
        <div class="item-block-horizontal">
            <div class="container-fluid">
                <div class="row mx-3 justify-content-md-start p-2">
                    <div class="col-1 p-1">
                        <a class="btn btn-outline-light btn-sm" asp-action="MyProfile" asp-controller="Account" asp-route-userName="@Context.User.Identity.Name">My Profile</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Posts" asp-controller="Admin">Posts</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Chats" asp-controller="Admin">Chats</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Users" asp-controller="Admin">Users</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Roles" asp-controller="Admin">Roles</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-include" style="width: 800px;">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Social_Media.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <div class="content">
        <div class="item-block-horizontal">
            <a asp-action="MyProfile" asp-controller="Account" asp-route-userName="@Context.User.Identity.Name">My Profile</a>
            <a asp-action="Posts" asp-controller="Admin">Posts</a>
            <a asp-action="Chats" asp-controller="Admin">Chats</a>
            <a asp-action="Users" asp-controller="Admin">Users</a>
            <a asp-action="Roles" asp-controller="Admin">Roles</a>
        </div>
        <div class="content-include" style="overflow:auto">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Social_Media.Web/Views/Shared/_ChatingRoomLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <div class="content">
        <div class="item-block-horizontal ">
            <div class="container-fluid">
                <div class="row mx-3 justify-content-md-start p-2">
                    <div class="col-1 p-1">
                        <a class="btn btn-outline-light btn-sm" asp-action="MyProfile" asp-controller="Account" asp-route-userName="@Context.User.Identity.Name">@Context.User.Identity.Name</a>
                    </div>        
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="MyPrivateChat" asp-controller="PrivateChat" asp-route-userName="@Context.User.Identity.Name">Massages</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="AllUsers" asp-controller="OtherAccount">Users</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Chats" asp-controller="Chat">Chats</a>
                    </div>        
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Posts" asp-controller="PostWall">Posts</a>        
                    </div>
                    @if (Context.User.IsInRole("Admin"))
                    {
                        <div class="col-1 p-1">
                            <a class="btn btn-outline-light btn-sm" asp-action="Posts" asp-controller="Admin">Admin</a> 
                        </div>
                    }
                </div>
            </div>        
        </div>
        <div class="content-include" style="width: 800px; height: 80vh">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Social_Media.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <div class="content">
        <div class="item-block-horizontal ">
            <div class="container-fluid">
                <div class="row mx-3 justify-content-md-start p-2">
                        @if (Context.User.Identity.Name != null)
                        {
                            <div class="col-1 p-1">
                                <a class="btn btn-outline-light btn-sm" asp-action="MyProfile" asp-controller="Account" asp-route-userName="@Context.User.Identity.Name">@Context.User.Identity.Name</a>
                            </div>
                        }
                        else
                        {   
                            <div class="col-1 p-1">
                                <a class="btn btn-outline-light btn-sm" asp-action="MyProfile" asp-controller="Account" asp-route-userName="@Context.User.Identity.Name">My Profile</a>
                            </div>
                        }
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="MyPrivateChat" asp-controller="PrivateChat" asp-route-userName="@Context.User.Identity.Name">Massages</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="AllUsers" asp-controller="OtherAccount">Users</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Chats" asp-controller="Chat">Chats</a>
                    </div>        
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Posts" asp-controller="PostWall">Posts</a>        
                    </div>
                    @if (!Context.User.Identity.IsAuthenticated)
                    {
                        <div class="col-1 offset-xl-8 p-1">
                            <a class="btn btn-outline-light btn-sm" asp-action="Login" asp-controller="Account">Log in</a>
                            <a class="btn btn-outline-light btn-sm" asp-action="Register" asp-controller="Account">Register</a> 
                        </div>
                    }
                    @if (Context.User.IsInRole("Admin"))
                    {
                        <div class="col-1 p-1">
                            <a class="btn btn-outline-light btn-sm" asp-action="Posts" asp-controller="Admin">Admin</a> 
                        </div>
                    }
                </div>
            </div>        
        </div>
        <div class="content-include overflow-auto">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Social_Media.Web/Views/Shared/_ProfileLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <div class="content">
        <div class="item-block-horizontal ">
            <div class="container-fluid">
                <div class="row mx-3 justify-content-md-start p-2">
                    <div class="col-1 p-1">
                        <a class="btn btn-outline-light btn-sm" asp-action="MyProfile" asp-controller="Account" asp-route-userName="@Context.User.Identity.Name">@Context.User.Identity.Name</a>
                    </div>        
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="MyPrivateChat" asp-controller="PrivateChat" asp-route-userName="@Context.User.Identity.Name">Massages</a>
                    </div>
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Chats" asp-controller="Chat">Chats</a>
                    </div>        
                    <div class="col-1 p-1" style="width: auto">
                        <a class="btn btn-outline-light btn-sm" asp-action="Posts" asp-controller="PostWall">Posts</a>        
                    </div>
                    @if (Context.User.IsInRole("Admin"))
                    {
                        <div class="col-1 p-1">
                            <a class="btn btn-outline-light btn-sm" asp-action="Posts" asp-controller="Admin">Admin</a> 
                        </div>
                    }
                </div>
            </div>        
        </div>
        <div class="content-include" style="overflow:auto">
            @RenderBody()
        </div>
    </div>
</body>
</html>