Social_Media.Web/Controllers/Account/User/ActionWithPassword/ActionPasswordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.Data.ViewModels.UserViewModels.PasswordViewModels;
using Social_Media.EntityFramework;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [AllowAnonymous]
    public class ActionPasswordController : Controller
    {
        private UserManager<User> _userManager;
        private UserContextEntityFramework _userContextEF;
        public ActionPasswordController(UserManager<User> userManager, UserContextEntityFramework userContextEF)
        {
            _userManager = userManager;
            _userContextEF = userContextEF;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByEmailAsync(model.Email);
                if (user != null)
                {
                    return RedirectToAction("ResetPassword", "Password", new {email = model.Email});
                }
            }
            return RedirectToAction("ForgotPassword", "Password");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByEmailAsync(model.Email);
                if (user != null)
                {
                    string code = await _userManager.GeneratePasswordResetTokenAsync(user);
                    var result = await _userContextEF.ResetPasswordAsync(user, code, model.Password);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Posts", "PostWall");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return RedirectToAction("ResetPassword", "Password", new {email = model.Email});
        }
    }
}

Social_Media.Web/Controllers/Account/User/ActionWithPassword/PasswordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.Data.ViewModels.UserViewModels.PasswordViewModels;
using Social_Media.EntityFramework;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [AllowAnonymous]
    public class PasswordController : Controller
    {
        public IActionResult ForgotPassword()
        {
            return View(new ForgotPasswordViewModel());
        }

        public IActionResult ResetPassword(string email)
        {
            return View(new ResetPasswordViewModel
            {
                Email = email
            });
        }
    }
}

Social_Media.Web/Views/Password/ForgotPassword.cshtml
@model ForgotPasswordViewModel

@{
    Layout = "_Layout";
}

<div>
    <h3>Please enter a email for reseting the password</h3>
    <form asp-action="ForgotPassword" asp-controller="ActionPassword"> 
        <div >
            <label asp-for="Email"></label>
            <input asp-for="Email" value="@Model.Email"/>
        </div>
        <button type="submit">Next</button>
    </form>
</div>

Social_Media.Web/Views/Password/ResetPassword.cshtml
@model ResetPasswordViewModel

@{
    Layout = "_Layout";
}

<div asp-validation-summary="All"></div>
<div>
    <form method="post"  asp-action="ResetPassword" asp-controller="ActionPassword"> 
        <div>
            <label asp-for="Email"></label>
            <input hidden="hidden" asp-for="Email" value="@Model.Email"/>
            <h3>@Model.Email</h3>
        </div>
        <div>
            <label asp-for="Password"></label>
            <input asp-for="Password" value="@Model.Password"/>
        </div>
        <div>
            <label asp-for="ConfirmPassword"></label>
            <input asp-for="ConfirmPassword" value="@Model.ConfirmPassword"/>
        </div>
        <button type="submit">Reset</button>
    </form>
</div>