Social_Media.Web/Controllers/Account/User/OtherUser/OtherAccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.Data.ViewModels.UserViewModels;
using Social_Media.EntityFramework;
using Social_Media.Web.Model.UserModel;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class OtherAccountController : Controller
    {
        private UserContextEntityFramework _userContextEF;
        public OtherAccountController(UserContextEntityFramework userContextEF)
        {
            _userContextEF = userContextEF;
        }

        public async Task<IActionResult> OtherProfile(string userName)
        {
            User user = await _userContextEF.GetAllUsers()
                .Include(user => user.UserFriends)
                .FirstOrDefaultAsync(user => user.UserName == userName);

            if (user != null)
            {
                return View(user);
            }
            return RedirectToAction("AllUsers");
        }

        public async Task<IActionResult> MyFriends(string userName)
        {
            User user = await _userContextEF.GetAllUsers()
                .Include(user => user.FollowingUser)
                .Include(user => user.UserFriends)
                    .ThenInclude(userAnother => userAnother.PrivateChats)
                .Include(user => user.UserFriends)
                    .ThenInclude(userAnother => userAnother.UserFriends)
                .Include(user => user.PrivateChats)
                .FirstOrDefaultAsync(user => user.UserName == userName);

            if (user != null)
            {
                return View(user);
            }
            return RedirectToAction("Posts", "PostWall");
        }


        public async Task<IActionResult> AllUsers()
        {
            User user = await _userContextEF
                .GetAllUsers()
                .Include(userInclude => userInclude.UserFriends)
                .FirstOrDefaultAsync(user => user.UserName == HttpContext.User.Identity.Name);

            return View(new UserAndAllUsersViewModel
            {
                UsersFromContext = _userContextEF.GetAllUsers()
                .Where(userContext =>
                       userContext.UserName != user.UserName &&
                       !user.UserFriends.Contains(userContext))
                .ToList(),

                User = user
            });
        }
    }   
}

Social_Media.Web/Controllers/PrivateChat/CrudPrivateChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.EntityFramework;
using Social_Media.Web.Infrastructure;
using Social_Media.Web.Model.UserModel;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class CrudPrivateChatController : Controller
    {
        private IRepositoryEntityFramework _contextEF;
        private UserContextEntityFramework _userContextEF;
        public CrudPrivateChatController(IRepositoryEntityFramework entityFramework, UserContextEntityFramework userContext)
        {
            _contextEF = entityFramework;
            _userContextEF = userContext;
        }

        [HttpPost]
        public async Task<IActionResult> CreatePrivateChat(FriendNameAndUserName model, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                User user = await _userContextEF.GetAllUsers()
                    .Include(user => user.PrivateChats)
                    .FirstOrDefaultAsync(user => user.UserName == model.UserName);

                User friendUser = await _userContextEF.GetAllUsers()
                    .Include(user => user.PrivateChats)
                    .FirstOrDefaultAsync(user => user.UserName == model.FriendName);

                bool existChat = user.PrivateChats.HasSamePrivateChat(friendUser.PrivateChats);

                if (user != null && friendUser != null && !existChat)
                {
                    PrivateChat privateChat = new PrivateChat
                    {
                        CreateAt = DateTime.Now,
                        UpdateAt = DateTime.Now,
                        Members = new List<User>() { user, friendUser}
                    };

                    await _contextEF.CreateAsync(privateChat);

                    if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("MyPrivateChat", "PrivateChat", new {userName = user.UserName});
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
            }
            return RedirectToAction("Posts", "PostWall");
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePrivateChat(PrivateChat privateChat, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                PrivateChat privateChatContext = await _contextEF.GetAll<PrivateChat>()
                                .Include(privateChatContext => privateChatContext.Members)
                                .Include(privateChatContext => privateChatContext.Massages)
                                .FirstOrDefaultAsync(privateChatContext => privateChatContext.Id == privateChat.Id);

                if (privateChatContext != null)
                {
                    privateChatContext.UpdateAt = DateTime.Now;
                    privateChatContext.Members = privateChat.Members;
                    privateChatContext.Massages = privateChatContext.Massages;

                    await _contextEF.UpdateAsync(privateChatContext);

                    if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Chats", "Chat");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
            }
            return RedirectToAction("Posts", "PostWall");
        }

        [HttpPost]
        public async Task<IActionResult> RemovePrivateChat(Guid privateChatId, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                PrivateChat privateChat = await _contextEF.GetAll<PrivateChat>()
                        .FirstOrDefaultAsync(privateChat => privateChat.Id == privateChatId);

                if (privateChat != null)
                {
                    await _contextEF.RemovetAsync(privateChat);

                    if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Chats", "Chat");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
            }
            return RedirectToAction("Posts", "PostWall");
        }
    }
}

Social_Media.Web/Controllers/PrivateChat/PrivateChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.EntityFramework;
using Social_Media.Web.Model.UserModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class PrivateChatController : Controller
    {
        private IRepositoryEntityFramework _contextEF;
        private UserContextEntityFramework _userContextEF;
        public PrivateChatController(IRepositoryEntityFramework entityFramework, UserContextEntityFramework userEntityFramework)
        {
            _contextEF = entityFramework;
            _userContextEF = userEntityFramework;
        }

        public async Task<IActionResult> PrivateChatingRoom(FriendNameAndUserName model)
        {
            var userContext = _userContextEF.GetAllUsers()
                .Include(user => user.PrivateChats);

            User user = await userContext
                .FirstOrDefaultAsync(user => user.UserName == model.UserName);

            User friendUser = await userContext
                .FirstOrDefaultAsync(user => user.UserName == model.FriendName);


            foreach (PrivateChat privateChat in user.PrivateChats)
            {
                var id = privateChat.Id;
                foreach (PrivateChat friendPrivateChat in friendUser.PrivateChats)
                {
                    var chatId = friendPrivateChat.Id;

                    if (id == chatId)
                    {
                       var privateChatContext = await _contextEF.GetAll<PrivateChat>()
                            .Include(privateChat => privateChat.Massages)
                            .FirstOrDefaultAsync(privateChat => privateChat.Id == id);
                        ViewBag.IdUser = user.Id;

                        return View(privateChatContext);
                    }
                }
            }

            return RedirectToAction("MyFriends", "Account", new {userName = user.UserName});
        }

        public async Task<IActionResult> MyPrivateChat(string userName)
        {
            User user = await _userContextEF.GetAllUsers()
                .Include(user => user.PrivateChats)
                    .ThenInclude(privateChat => privateChat.Members)
                .Include(user => user.Massages)
                .FirstOrDefaultAsync(user => user.UserName == userName);

            if (user != null)
            {
                return View(user.PrivateChats.AsEnumerable());
            }
            else
            {
                return RedirectToAction("Posts", "PostWall");
            }
        }
    }
}

Social_Media.Web/Controllers/User/OtherActionAccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media.Data.DataModels.Entities_Identity;
using Social_Media.EntityFramework;
using Social_Media.Web.Model.UserModel;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Social_Media.Web.Controllers
{
    [Authorize]
    public class OtherActionAccountController : Controller
    {
        private UserContextEntityFramework _userContextEF;
        public OtherActionAccountController(UserContextEntityFramework userContextEF)
        {
            _userContextEF = userContextEF;
        }

        [HttpPost]
        public async Task<IActionResult> AddFriendToUser(FriendNameAndUserName model, string returnUrl = "")
        {
            User userFriend = await _userContextEF.GetAllUsers()
                .FirstOrDefaultAsync(user => user.UserName == model.FriendName);

            User user = await _userContextEF.GetAllUsers()
                .Include(user => user.UserFriends)
                .FirstOrDefaultAsync(user => user.UserName == model.UserName);

            if (userFriend != null && user != null)
            {
                user.UserFriends.Add(userFriend);

                await _userContextEF.UpdateUserAsync(user);

                if (string.IsNullOrEmpty(returnUrl) || string.IsNullOrWhiteSpace(returnUrl))
                {
                    return RedirectToAction("MyProfile", "Account", new { userName = model.UserName });
                }
                else
                {
                    return Redirect(returnUrl);
                }
            }
            return RedirectToAction("MyProfile", "Account", new { userName = model.UserName });
        }
    }   
}

Social_Media.Web/Views/OtherAccount/AllUsers.cshtml
@model UserAndAllUsersViewModel

@{
    Layout = "_ChatingRoomLayout";
    ViewBag.Title = "All users";
}

<div>
    <h4 class="text-center">All Users</h4>
    <div class="border-top mx-3">
        @if (Model.UsersFromContext.Count() > 0)
        {
            @foreach (User user in Model.UsersFromContext)
            {
                <div class="m-3 card" style="width: 400px">
                    <div class="card-body d-flex justify-content-between">
                        <div>
                            <h5>@user.UserName</h5>
                        </div>
                        <div>
                            <form asp-action="AddFollowToUser" asp-controller="OtherActionAccount">
                                <input hidden="hidden" name="UserName" value="@Model.User.UserName">
                                <input hidden="hidden" name="FriendName" value="@user.UserName">
                                <button class="btn btn-secondary p-1" type="submit">Follow</button>
                            </form>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h5>Users is not exist</h5>
        }
    </div>
</div>

Social_Media.Web/Views/OtherAccount/MyFriends.cshtml
@model User

@{
    Layout = "_Layout";
    ViewBag.Title = "Friends";
}

<div>
    @if (Model.UserFriends.Count > 0)
    {
        <div class="text-center m-1">
            <h4>My friends</h4>
        </div>
    }
    else
    {
        <div class="text-center m-1">
            <h4>You don't have friends</h4>
        </div>
    }
    
    @foreach (User user in Model.UserFriends)
    {
        <div class="card m-2">
            <div class="card-body d-flex justify-content-between">
                <div>
                    <h4>Name: @user.UserName</h4>
                </div>
                <div class="d-flex">
                    <div class="mx-1">
                        <form asp-action="RemoveFromFriend" asp-controller="OtherActionAccount">
                            <input hidden="hidden" name="FriendName" value="@user.UserName">
                            <button class="btn btn-secondary p-1" type="submit">Remove from friend</button>
                        </form>
                    </div>
                    <div class="mx-1">
                        @if (user.UserFriends.Contains(Model))
                        {
                            @if (user.PrivateChats.HasSamePrivateChat(Model.PrivateChats))
                            {
                                <form asp-action="PrivateChatingRoom" asp-controller="PrivateChat">
                                    <input hidden="hidden" name="UserName" value="@Model.UserName">
                                    <input hidden="hidden" name="FriendName" value="@user.UserName">
                                    <button class="btn btn-secondary p-1" type="submit">Send massage</button>
                                </form>
                            }
                            else
                            {
                                <form asp-action="CreatePrivateChat" asp-controller="CrudPrivateChat">
                                    <input hidden="hidden" name="model.UserName" value="@Model.UserName">
                                    <input hidden="hidden" name="model.FriendName" value="@user.UserName">
                                    <button class="btn btn-secondary p-1" type="submit">Start a conversation</button>
                                </form>
                            }
                        }
                        else
                        {
                            <button class="btn btn-secondary p-1" disabled="disabled" type="button">You are followed</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@if (Model.FollowingUser.Where(user => !user.UserFriends.Contains(Model)).Count() != 0)
{
    <div class="mt-3 border-top">
        <div class="text-center m-1">
            <h4>Followed user</h4>
        </div>
        @foreach (User userFollowed in Model.FollowingUser)
        {
            <div class="card m-2">
                <div class="card-body d-flex justify-content-between">
                    <div>
                        <h4>Name: @userFollowed.UserName</h4>
                    </div>
                    <div>
                        <form asp-action="AddFriendToUser" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()" asp-controller="OtherActionAccount">
                            <input hidden="hidden" name="UserName" value="@Model.UserName">
                            <input hidden="hidden" name="FriendName" value="@userFollowed.UserName">
                            <button class="btn btn-secondary p-1" type="submit">Add as Friends</button>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
}

Social_Media.Web/Views/OtherAccount/OtherProfile.cshtml
@model User 

@{
    Layout = "_ProfileLayout";
}

<div>
    <h3>Name: @Model.UserName</h3>
    <h4>Email: @Model.Email</h4>
    <h4>Friends: @Model.UserFriends.Count</h4>
</div>